### ISSUE TITLE
Adding new test classes in Visual Studio 2017 leads to exception

### ISSUE THREAD

**Issue by firehirsch** [testcop/Resharper.TestCop#11]
If you use TestCop to add a new class with tests in VIsualStudio 2017 with R# 2017.2 the following error is shown and VisualStudio crashes.

![image](https://user-images.githubusercontent.com/8678671/32167286-c3132a04-bd68-11e7-9960-768654206880.png)

The class file gets created but is not added to the project.

**Comment by testcop** [comment]
Hi firehirsch, I have a couple of questions:
* Which version of TestCop are you using. Is it the EAP version?
* If you are able to share the RegEx patterns you are using then that would help too.
* Which template do you have TestCop configured to use when creating the class? Is it just 'class' ?

I'll download VS2017 in the meantime....

**Comment by firehirsch** [comment]
Here my answeres:

I used 1.10.4.5-EAP. But I didn't notice that I have installed this PreRelease. I'll try later with the last normal release.
My RegEx patterns:
Test Namespace RegEx: ^(.*?)\.?UnitTests$
Test Namespace RegEx Replace: (empty)

With version 1.10.4.6-EAP I get the following output:
`Setting keyboard shortcut for 'Resharper.ReSharper_JumpToTestFile' to 'Global::Ctrl+G, Ctrl+T'
Setting keyboard shortcut for 'ReSharper_TestCopUnitTestRunContext' to 'Global::Ctrl+G, Ctrl+X'
Error calculating sub namepsace HttpMock.UnitTests<>
Error calculating sub namepsace HttpMock.UnitTests<>
Error calculating sub namepsace HttpMock.UnitTests<>
Error calculating sub namepsace HttpMock.UnitTests<>
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests<>
Error calculating sub namepsace HttpMock.UnitTests<>
Error calculating sub namepsace HttpMock.UnitTests<>
Error calculating sub namepsace HttpMock.UnitTests<>
Unable to identify the class from current cursor position.
Hunted and found first name in file to be HttpMock.RequestResponse.RequestDefinition
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
Error calculating sub namepsace HttpMock.UnitTests.RequestResponse<>.RequestResponse
`

**Comment by testcop** [comment]
I am having trouble replicating this issue. It works for me with my sample projects.
* Does it always crash or is it only when navigating from certain files?
* Is HttpMock.UnitTests.RequestResponse an actual code class within the project or just an instance of the class in the unit test class?
* Is the file you are navigating *from* ... a file in the root? Or in a subdirectory which does not provide namespace?

Is it possible for you to create a simple project which replicates the issue?

**Comment by firehirsch** [comment]
- It crashes all the time when a new testclass should be added. I've not tried it yet with existing testclasses
- HttpMock.UnitTests.RequestResponse is a namespace where the class to test is in.

I've attached my project with that I found that problem. SO you can try it with this.

[src.zip](https://github.com/testcop/Resharper.TestCop/files/1433993/src.zip)

**Comment by testcop** [comment]
It was the 'virtual folders' you had in your project which my recent work didn't handle. I have fixed the logic and it appears to work as expected with your project. Please confirm either way.  [1.10.4.7-EAP](https://resharper-plugins.jetbrains.com/packages/Resharper.TestCop.R9/1.10.4.7-EAP)

**Comment by firehirsch** [comment]
I've just installed your new EAP version and it looks good. No crashes and no logged errors in the output window.
