### ISSUE TITLE
TestCop is marked not compatible since I updated to ReSharper 2023.3

### ISSUE THREAD

**Issue by blazcowicz** [testcop/Resharper.TestCop#110]
I have recently discovered TestCop and it's one of my most used ReSharper extensions, so I was quite disappointed to discover it didn't work anymore. I have recently updated my project to .NET 8, along with Visual Studio going to version 17.8.3 and ReSharper to 2023.3. Seeing other closed issues here, it looks like the reason should be ReSharper's new version.

It would be great if you could update it. Thanks for all your hard work!

**Comment by testcop** [comment]
updated submitted to JetBrains. Should be available within a couple of days
