### ISSUE TITLE
When generating files, adhere to non-namespace-providing folders, e.g. "src"

### ISSUE THREAD

**Issue by cmeeren** [testcop/Resharper.TestCop#2]
In my non-test projects, I have all code placed in a top-level "src" folder. When generating a test file using TestCop, the new test file is not placed in a "src" folder in the test project. Example:

Folder structure in real project:

```
MyProject
  src
    Customer
      Customer.cs
    Order
      Order.cs
```

Actual folder structure in test project, as generated by TestCop:

```
MyProjectTests
  Customer
    CustomerTests.cs
  Order
    OrderTests.cs
```

Desired folder structure in test project, as generated by TestCop:

```
MyProjectTests
  src
    Customer
      CustomerTests.cs
    Order
      OrderTests.cs
```

**Comment by testcop** [comment]
Hello, I avoid folders containing code that aren't NamespaceProviders. My thinking is that if I have that many files in a folder then perhaps I need to restructure the namespaces. However, I can see your case is different.

With some work it should be possible to implement but adding full support will need to consider multiple NamespaceProviders=false folders.

I will definately take a look

**Comment by testcop** [comment]
This is still work in progress (admittedly a background task) as it has proved quite complex to implement as testcop has to support 3 different types of test project configuration.

**Comment by testcop** [comment]
Released an update as an EAP of TestCop - please confirm if fix works for you.
[1.10.4.5-EAP](https://resharper-plugins.jetbrains.com/packages/Resharper.TestCop.R9/1.10.4.5-EAP)

**Comment by cmeeren** [comment]
Sorry, I'm currently deep into F# and won't get the opportunity or time to test TestCop for a while. If it seems fixed for you, feel free to close this. :)

**Comment by testcop** [comment]
Closing as fixed. Released changes
