### ISSUE TITLE
Upgrade to 2018.3?

### ISSUE THREAD

**Issue by espenalb** [testcop/Resharper.TestCop#28]
Is there a timeline for TestCop support for R# 2018.3?

**Comment by testcop** [comment]
today !

**Comment by testcop** [comment]
Released … [1.10.6.3](https://resharper-plugins.jetbrains.com/packages/Resharper.TestCop.R9/1.10.6.3)

**Comment by mario-d-s** [comment]
Thanks a bunch!

**Comment by hansmelin** [comment]
I have updated R# to 2018.3.2 and now I can´t find TestCop in the Extension Manager

**Comment by testcop** [comment]
will fix this weekend

**Comment by testcop** [comment]
I have encountered a problem with the new Jetbrains package manager portal which no longer likes the 'id' of my nuget package. I currently can't push a new release out.

**Comment by testcop** [comment]
Uploaded to portal - received a message it might take 48hrs
Keep me posted and apologies for the delay...

**Comment by hansmelin** [comment]
Now it works. Thanks!
