### ISSUE TITLE
Upgrade to 2019.1.1

### ISSUE THREAD

**Issue by hansmelin** [testcop/Resharper.TestCop#34]
Hello!

There is a new version of R# out now, 2019.1.1

Could you please update TestCop?

**Comment by vdasus** [comment]
17 days... Any news? Really helpful plugin

**Comment by rayphi** [comment]
As workaround you can get my fork (Pull Request  #35) build and install the package local (see: [ReSharper DevGuide > Local Installation](https://www.jetbrains.com/help/resharper/sdk/Extensions/Deployment/LocalInstallation.html))

**Comment by vdasus** [comment]
If we'll need to wait a few days - i'll wait, but then i will try to take your fork, thank you

**Comment by testcop** [comment]
I missed the GitHub notification for this thread, I will take a look and thanks @rayphi for the pull request

**Comment by testcop** [comment]
released [testcop](https://plugins.jetbrains.com/plugin/11635-testcop-for-resharper-2019-1-1)
I am getting test failure within AppVeyor too

**Comment by hansmelin** [comment]
I have tested and it works.
Thanks!
