### ISSUE TITLE
Upgrade to 2019.3

### ISSUE THREAD

**Issue by rayphi** [testcop/Resharper.TestCop#43]
Groundhog Day 😜

**Comment by rayphi** [comment]
Is it possible to offer support for this task?
So that for example you only have to accept a pull request?

**Comment by testcop** [comment]
I've had a quick look and I am getting nuget dependency errors when attempting to upgrade - it may take me a few evenings to work it out...

**Comment by testcop** [comment]
Waiting on Jetbrains fix..
https://groups.google.com/forum/#!topic/resharper-plugins/pYN7loKKrko

**Comment by schuettecarsten** [comment]
Please try again with R# 2019.3.1

**Comment by Mike-EEE** [comment]
Please feel free to vote to improve the extension model experience so we don't have to continually nag extension model authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

I've mentioned this issue in the comments.

**Comment by testcop** [comment]
New version recompiled and pushed - may 48hrs to appear for download...

**Comment by schuettecarsten** [comment]
Testcop still not found in R# extension manager?

**Comment by MO2k4** [comment]
It is waiting for approval by jetbrains and because of the holidays it is taking a little bit longer than usual



Am 27.12.19 um 07:30 schrieb Carsten Schuette
