### ISSUE TITLE
Upgrade to 2020.1

### ISSUE THREAD

**Issue by grzesiek-galezowski** [testcop/Resharper.TestCop#47]
Hi, please enable the extension for 2020.1.

Many thanks for a great extension!

**Comment by Mike-E-wins** [comment]
A kind reminder to upvote the following issue to improve the upgrade experience around R# extensions here:

https://youtrack.jetbrains.com/issue/RSRP-459966

I see that @grzesiek-galezowski voted.  Thank you and to all who have also voted for your support!

**Comment by testcop** [comment]
yep - I was just waiting on EAP to end..

**Comment by testcop** [comment]
new build submitted to JetBrains - it will take a couple of days to become available
