### ISSUE TITLE
Warnings for `AssemblyAttributes.cs` (Generated File)

### ISSUE THREAD

**Issue by Mike-E-angelo** [testcop/Resharper.TestCop#51]
Using [this commit here](https://github.com/DragonSpark/Framework/commit/833139de2f54f599972b3f5878734d20e8633896), I am seeing warnings of the like:

![](https://i.imgur.com/kPZtNq4.png)

These appear to be generated files, and wanted to report this here in the case there is an obvious setting/configuration that I am overlooking or if perhaps this is a bug.

**Comment by testcop** [comment]
I will take a look. The logic is in here https://github.com/testcop/Resharper.TestCop/blob/8b743dbe329a5cc7f20d46c3008e0344385727b0/Project/Src/TestCop.Plugin/ProjectAnalysisElementProcessor.cs

As a 'quick fix' you could set the orphaned files value in TestCop settings to be '*.xxx' so it only checks for a file extension that won't exist.

**Comment by Mike-E-wins** [comment]
OK cool thank you for the suggestion.  To be sure, if I wanted to check for a file extension that didn't exist, shouldn't I just disable orphaned files?  Trying to understand the difference between the two.

**Comment by testcop** [comment]
Fix on the way - I discovered the method currentProject.GetIntermidiateDirectories()
Only one orphaned file reported against dragonspark

**Comment by Mike-E-wins** [comment]
Woohoo!  Thank you very much @testcop!

**Comment by testcop** [comment]
Published to jetbrains - it should be approved in a couple of days.

**Comment by Mike-E-angelo** [comment]
Closing this issue as it is fixed.  Thank you for your efforts here!
