### ISSUE TITLE
Possible Issue with Shortcuts

### ISSUE THREAD

**Issue by Mike-E-angelo** [testcop/Resharper.TestCop#53]
I seem to be having problems with applying a shortcut for Jump-to-Test.  I apply a shortcut but it goes away on the next start of Visual Studio.  The issue is being tracked here:

https://youtrack.jetbrains.com/issue/RSRP-480735

What made me suspect there is an issue in the extension here is that there is output in the console window on startup:

![](https://i.imgur.com/6u5NsbC.png)

It doesn't mention the keyboard shortcut that I saved.  Could it be possible it is being overridden somehow?

**Comment by Denis-Korneev** [comment]
There are two issues:
1. There could be more than one keybindings assigned to a command. The plugin should not clear shortcuts assigned by user (see DTEHelper.AssignKeyboardShortcutIfMissing).
2. ReSharper never assigns any shortcuts without user's confirmation. That's a rule. ForceKeyboardBindings should not be called from the daemon stage.

**Comment by testcop** [comment]
The shortcut testcop assigns is configured via the testcop options page. 
The Resharper plugin framework is pretty bad for supporting shortcuts (it keeps clearing them for extensions) so the plugin reassigns on start. It logs this...trying to be helpful :)

**Comment by Mike-E-angelo** [comment]
Ah!  OK, that is good to know.  There is still the issue that it sounds like the extension is breaking a R# rule/norm, but I am now unblocked by using the options, thank you. 👍

Would it be possible to perhaps update the message in the Output Window to reflect this?  Something like `To change these shortcuts, visit the TestCop Options page.`  That way we aren't having to think things are broken and resort to opening new issues in the R# repository. 😁

One question though: is it possible to have multiple keyboard shortcuts?  I want to retain the default but add one like the Keyboard options in Visual Studio.

**Comment by testcop** [comment]
The keyboard mapping UI in Visual Studio only permits one shortcut mapping within the same context. I don't think you can have multiple.

**Comment by Mike-E-angelo** [comment]
Maybe there's a miscommunication here.  This is what I am referring to:

![](https://youtrack.jetbrains.com/api/files/74-902395?sign=MTU5NzUzNjAwMDAwMHwxMS0xOTkxMnw3NC05MDIzOTV8M2UwVUdKUEtWTks4Z24ybmh4ck4zdGZT%0D%0AWWJBSUl6aUpNQ1JGTkZxanBFVQ0K%0D%0A&updated=1597212269950)

After assigning as such, I am able to use either shortcut and the command executes.  But of course this only works for the current session.  Closing Visual Studio and re-opening erases this with the shortcut defined in the TestCop options.

**Comment by Denis-Korneev** [comment]
Visual Studio **does** allow many shortcuts for one command in the same shortcut scope. That's exactly what Mike did.
`if (currentBindings.Length == 1)` in `AssignKeyboardShortcutIfMissing` is a bug.

**Comment by Denis-Korneev** [comment]
Applying shortcuts silently on every startup is not a good idea for many reasons. The main of them is that the user could manually reassign any shortcut. 

We should not make any assumption on the "right" state of shortcuts. User could use another shortcut (or shortcuts) for TestCop commands and vice versa use TestCop's shortcuts for other commands just because it's more convenient for him.

The only place to apply shortcuts is an option page with explicit notification to the user.

**Comment by testcop** [comment]
In the options page of TestCop (accessed via Resharper) there was a tab for the keyboard shortcut. This has now been removed.
TestCop continues to printout to the panel when it maps the shortcut and also prints out the existing shortcuts used on start.
TestCop will default its shortcuts only on installation if no existing shortcuts are set.
Going forward...to change the mappings - use visual studio keyboard options tab...

**Comment by Mike-E-angelo** [comment]
Thank you again for all your efforts and collaboration towards getting this resolved!
