### ISSUE TITLE
TestCop breaks Code Inspection / Inspection Severity option page

### ISSUE THREAD

**Issue by neustakwesling** [testcop/Resharper.TestCop#58]
When I install the TestCop extension, the option page under Options/Code Inspection/Inspection Severity breaks.
It only shows an empty page and to chose from the pages below. 

Expected behaviour: The tree for the different languages are shown and severity can be set up.

![Inspection Severity without TestCop](https://user-images.githubusercontent.com/13115992/93429884-210c0080-f8c2-11ea-8eee-77864698b675.png)

![Inspection Severity with TestCop](https://user-images.githubusercontent.com/13115992/93429836-10f42100-f8c2-11ea-9fb1-e4a0c619f06a.png)

Best regards

**Comment by testcop** [comment]
I will take a look...

**Comment by testcop** [comment]
Fixed built and pushed to Jetbrains.
