### ISSUE TITLE
Upgraded ReSharper to 2020.3, TestCop stops showing in Extension Manager and stops responding to Ctrl+G, Ctrl+T

### ISSUE THREAD

**Issue by astrohart** [testcop/Resharper.TestCop#60]
NOTE: In the below, "R#" refers to "ReSharper".  (Saves typing).

I am utilizing Visual Studio 2019 16.8.3 on Windows 10 Pro, Build 2204, with R# 2020.3.

I always like to keep all the software on my computer at the very latest version.

Previously, I was going with R# 2020.2, and I went to the R# 2020.3 and it seems like all TestCop functionality just vanished.

**Comment by testcop** [comment]
I need to recompile with the latest  R# library. I gave it a try last week and though there appears to be just a couple of functions impacted I haven't been able to work out their new alternatives.

**Comment by astrohart** [comment]
Thanks so much for your kind attention and consideration of my request!  I am eagerly awaiting the release for the latest version of R#.

**Comment by astrohart** [comment]
I think it is bad programming practice on the authors  of the R# lib -- and this is totally without any context -- but it seems like they should always be backwards-compatible in their coding so that new functionality does not break existing interfaces.

**Comment by Mike-E-angelo** [comment]
So should this issue be closed yet?  It would seem it is not available yet for 2020.3.  BTW @astrohart if you would like, please upvote this issue which basically is monitoring the very painful upgrade process of R#:

https://youtrack.jetbrains.com/issue/RSRP-459966

We're all whining and complaining about it there. 😁😇😆

**Comment by testcop** [comment]
Apologies but I am stuck on some compilation errors from latest R# version and will need to dig deeper into R# code.

Pull requests gratefully accepted !

**Comment by Mike-E-angelo** [comment]
I've put out the bat-signal:

https://twitter.com/Mike_E_angelo/status/1343900946808639488

🙏

**Comment by astrohart** [comment]
Issue upvoted on the YouTrack website.  I have a question, could this solution be re-architected into a Visual Studio extension (that you do not need ReSharper for, necessarily?) 

It seems to me that there would be plenty of ways that the exact same functionality could be duplicated purely utilizing the EnvDTE interfaces that Visual Studio exposes, i.e., by turning TestCop into a .vsix.  I mean, all the extension really does (in my mind) is keep track of which class is being edited and uses CTRL+G,CTRL+T shortcut to switch back and forth from the corresponding unit test class (or manufacture a new one) solely based on, e.g., regex and pattern matches.

I strongly recommend you consider "divorcing" this extension from R# and just make it a VSIX that installs via the Visual Studio Extension Manager.

**Comment by matkoch** [comment]
@testcop We have a plugin-developer Slack channel - if you want, I can invite you, I would just need your e-mail address. I already updated part of the repository to use our plugin template, which should make updating and publishing a lot easier. I admit the process has been a pain, but that should not be the case any longer.

Ensuring backward-compatibility is unfeasible, unfortunately. Firstly, in principle, our whole codebase is public API, but very very little of that is actually used in plugins. There are numerous reasons for changing code, like architectural requirements (for instance ReSharper OOP), performance improvements, or language updates (C# 8, 9, etc.). Even putting Obsolete attributes onto APIs would already put a large burden onto development for very little benefit. Our solution to that is the mentioned plugin developers channel, where we can give help more targeted.

**Comment by testcop** [comment]
Thanks for your repo changes @matkoch - plugin rebuilt

**Comment by matkoch** [comment]
did you already use what i've pushed? i'd still need to check a couple of things, but it should already compile again

**Comment by testcop** [comment]
My unit tests pass and basic manual tests work as expected. I will take a look at the other repo change you make and apply. What are the features of the plugin template??

I will send you my email address separately...

**Comment by matkoch** [comment]
Just like i said: allows for easier updating the SDK (PackageReference) and
has scripts for publishing and visual studio debugging. If you can get rid
of DTE (at least partially), you can also publish for Rider.

**Comment by testcop** [comment]
Unfortunately - DTE is essential to register the shortcut the plugin uses...there is whole separate support thread on that topic....https://youtrack.jetbrains.com/issue/RSRP-480735 and also to refresh the VS UI when a new file is added to the project.

If R# could support plugin shortcuts better then DTE dependency could probably be dropped...

**Comment by matkoch** [comment]
That doesn’t sound like smth that couldn’t be implemented using the SDK,
but lets talk on slack then.

**Comment by astrohart** [comment]
The latest and greatest of TestCop downloaded and installed for me!  Thanks!
