### ISSUE TITLE
ReSharper 2020.3.3 has come out

### ISSUE THREAD

**Issue by astrohart** [testcop/Resharper.TestCop#63]
You might want to update the code :-)  TestCop is my favorite R# extension and it goes dead every time R# puts out another version.

**Comment by Mike-E-angelo** [comment]
So nice to have someone else with the case of the nags... now I no longer feel like an ubernag. 😆

We nag because we care. 😁

**Comment by Mike-E-angelo** [comment]
BTW I don't think a new install/update is required for minor versions.  If `2020.3.3` is released, then any extension with a `2020.3.x` install will work.  This trips me up all the time as well.

**Comment by Mike-E-angelo** [comment]
Looks like `2021.1 Beta` is out and can be used to build against for RTM:

https://youtrack.jetbrains.com/issue/RSRP-459966#focus=Comments-27-4792715.0-0

**Comment by astrohart** [comment]
It would be my strong encouragement to try and stay ahead of the R# update curve as is possible.  Then the extension can have as much of an uninterrupted availability as possible.
