### ISSUE TITLE
R# 20201.1 Beta Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [testcop/Resharper.TestCop#64]
Looks like https://github.com/testcop/Resharper.TestCop/issues/63#issuecomment-807384373 was closed but the cause remains:
https://youtrack.jetbrains.com/issue/RSRP-459966#focus=Comments-27-4792715.0-0

😁

Maybe @matkoch can assist.

😁😁😁

**Comment by matkoch** [comment]
I don't know how I can be of particular help here?

**Comment by Mike-E-angelo** [comment]
That was in reference to #60.  Hoping for more of a good thing. 😇
