### ISSUE TITLE
R# 2021.1 broke TestCop

### ISSUE THREAD

**Issue by astrohart** [testcop/Resharper.TestCop#65]
I am using VS 2019 Enterprise v16.9.3 and R# 2021.1 which just came out.

Please update TestCop to be compatible.  Thanks!

**Comment by vdasus** [comment]
please

**Comment by Mike-E-angelo** [comment]
Friendly reminder to upvote this issue here which asks the R# team to alleviate the pain of extension updates with each R# release:

https://youtrack.jetbrains.com/issue/RSRP-459966

**Comment by vdasus** [comment]
please, again...

**Comment by MarkSandy** [comment]
You can compile it yourself and install it via local nuget.
You need to edit the nuget.build.bar though.
1. restore all nuget packages (rightclick on the solution)
2. configure the OUTDIR to point to your local binary output folder
2. As Jetbrains.Platform.SDK hasn't been updated yet, you need to manually set the WAVEID to 211 in line 15
3. Edit and update the Testcop.nuspec file to show the new version number and target R# version
4. build and install the local nupkg according to the description on the jetbrains help page

**Comment by Mike-E-angelo** [comment]
If it's that easy @MarkSandy can't those steps be put into a pull request, merged into main, and be officially deployed from there?

**Comment by astrohart** [comment]
To be fair, I have never heard of that process before, needless to say, half the tools you mention.

I also find myself a little too short of time to prioritize doing this myself on any kind of dependable basis.

**Comment by EdvardasDlugauskas** [comment]
Just a heads up: we are trying to coordinate a PR to help Mark out with an official release of the NuGet in #68

**Comment by MarkSandy** [comment]
I would could create a pull request, but this would add some "hacking" (e.g. overriding the waveid) which I wanted to avoid.

**Comment by testcop** [comment]
Oh no,  for some reason notification emails have stopped on this repo and I missed all this conversation.

Really really sorry.... I am looking at it now...
