### ISSUE TITLE
Doc: Hotkey/shortcut option is not there anymore

### ISSUE THREAD

**Issue by rklec** [testcop/Resharper.TestCop#76]
The doc in https://github.com/testcop/docs/blob/master/wiki/keyboard_shortcut.md explains you should find the option for the hot key in the TestCop options, but it is not there:
![grafik](https://user-images.githubusercontent.com/71322635/133642509-bb8a0943-2b9f-4ac3-87af-ee6f9ecfdf89.png)

And I have no idea what "Show panel when mappng keyboard shortcut" means. 😅 

TestCop v1.10.14.1
VS 2019

BTW in (German?) Visual Studio 2019 versions Strg+G binds to "Go to line" and thus without adjusting that option, the feature of TestCop is just not usable (nobody wants to use a menu for that). Maybe you could consider changing the default shortcut.

**Comment by testcop** [comment]
Documentation is now updated - the UI setting was dropped once R# added support for running [code on installation](https://github.com/testcop/Resharper.TestCop/blob/7effad6233a0f4e93b7168c7b1dc5477494149b3/Project/Src/TestCop.Plugin/RegisterKeyboardShortcuts.cs#L24).

The shortcut is assigned once on installation....you are free to change it afterwards to your favourite key combination

**Comment by testcop** [comment]
+ the show panel when mapping shortcut....
this shows the TestCop panel in the VS screen when the macro is mapped ...so you know which mapping was used...
