### ISSUE TITLE
R# 2021.3 EAP Support

### ISSUE THREAD

**Issue by rayphi** [testcop/Resharper.TestCop#79]
To be able to quickly provide the VS2022 support.

**Comment by rayphi** [comment]
currently the automatic shortcut assignment does not work.
and an exception that EnvDTE cannot be found is thrown when the JumpToTestFile action.
But besides that, it works quite well.

**Comment by testcop** [comment]
`exception that EnvDTE cannot be found is thrown`
any ideas if this is an R# or VS change? I am assuming it is VS...

**Comment by rayphi** [comment]
This is an VS change

https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/breaking-api-list?view=vs-2022#dte-and-_dte-type-cast-failures

In `Project\Src\TestCop.Plugin\Helper\DTEHelper.cs` we use EnvDTE
