### ISSUE TITLE
Move File No Longer Works

### ISSUE THREAD

**Issue by Mike-E-angelo** [testcop/Resharper.TestCop#84]
Hi all,

First off, thank you so much for putting this together for the latest ReSharper build.  It is much appreciated.

Seeing that it was available, I checked it out and was met with warnings of files not corresponding to the correct namespace.

For instance, this file:
https://github.com/DragonSpark/Framework/blob/0347d51de251baf0b954d57f06debaa5f1d8012b/DragonSpark.Application.Testing/Compose/Entities/Queries/ContextQueryAdapterTests.cs

Which I renamed to `ContextsTests` and was provided a prompt to move it:

![](https://bit.ly/3DLabPJ)

Unfortunately, when doing so, nothing happen.

Also worth noting: there appears to be a typo in the command: `file file`

Thank you for any consideration towards addressing this. 🙏

**Comment by testcop** [comment]
thanks for raising. it is one of the areas I was never able to write a decent unit test for

**Comment by rayphi** [comment]
Created an Issue over here => https://youtrack.jetbrains.com/issue/RSRP-487230 because TestCop is not mentioned in the exception that was trown.

**Comment by rayphi** [comment]
As mentioned in [RSRP-487230](https://youtrack.jetbrains.com/issue/RSRP-487230) the `AssemblyCompanyAttribute` solves this issue.

**Comment by Mike-E-angelo** [comment]
Thank you for all your efforts here!  It is very cool to see, and the quick turnaround is especially appreciated. 🙏

**Comment by testcop** [comment]
RELEASED https://plugins.jetbrains.com/plugin/11635-testcop-for-resharper-2021-3/versions/stable/150909

**Comment by testcop** [comment]
@rayphi you are a star...
