### ISSUE TITLE
Testcop don't work

### ISSUE THREAD

**Issue by MichaelInsberg** [testcop/Resharper.TestCop#86]
I installed the plugin but I can't see it in Resharper Options and the shortcut also won't work.

I'm using VS2022 wit the latest version of resharper.

Any suggestions?

Greeting michael

**Comment by testcop** [comment]
Just checked with
Microsoft Visual Studio Community 2022 Preview (64-bit)
Resharper 2021.3.1..

and installed v2021.3 Testcop Version **1.10.15.6**

All works as expected.

**Comment by MichaelInsberg** [comment]
I started repair Resharper after that everthing works perfect.
