### ISSUE TITLE
Focus jumps to TestCop output making it impossible to continue to work

### ISSUE THREAD

**Issue by MarkSandy** [testcop/Resharper.TestCop#87]
I am making changes in a test class that does not fit the current naming convention. So I get the error message

"Didn't find project with namespace of: yxxxx to match xxxx.Unittests.xxxxx"

Which is ok. 

However, the focus switches from the code view to the TestCop output view making it impossible to continue to work fluently as I always have to click into the code window to continue typing. The message appears after every keystroke.

**Comment by testcop** [comment]
hi, that message should only appear when you use the testcop shortcut to navigate between test and code. The shortcut by default is assigned to Ctrl-G+T. Can you confirm versions of R# and VisualStudio you are using please?

I see the focus changing only when i do Ctrl-G+T...I will take a look at why it has started doing this...

**Comment by MarkSandy** [comment]
Hi,
the message (and focus change) appears after each end every keystroke. However, the focus should not change at all, don’t you think so? I changed the shortcut to Ctrl-Y Y (Y is on the lower left, right next to Ctrl on a german keyboard)

The problem shows up on VS 2022 and R# 2021.3.3.

I tried to reproduce the problem but failed. I will continue to work and keep an eye on the strange behavior.

Kind regards

Mark




Mark Sandy
Senior Lead IT Architect


Mobil +49 151 544 22 470
***@***.***
Voßstraße 33, 10117 Berlin

MaibornWolff GmbH, Theresienhöhe 13, 80339 München
www.maibornwolff.de, Telefon +49 89 544 253 000
USt-ID DE 129 299 525, Amtsgericht München HRB 98058
Geschäftsführer: Volker Maiborn, Holger Wolff,
Alexander Hofmann, Florian Theimer, Marcus Adlwart

_______________________________________________

Von: Reporting for duty ***@***.***>
Gesendet: Montag, 7. Februar 2022 22:12
An: testcop/Resharper.TestCop ***@***.***>
Cc: Mark Sandy ***@***.***>; Author ***@***.***>
Betreff: Re: [testcop/Resharper.TestCop] Focus jumps to TestCop output making it impossible to continue to work (Issue #87)


hi, that message should only appear when you use the testcop shortcut to navigate between test and code. The shortcut by default is assigned to Ctrl-G+T. Can you confirm versions of R# and VisualStudio you are using please?

I see the focus changing only when i do Ctrl-G+T...I will take a look at why it has started doing this...

—
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2ftestcop%2fResharper.TestCop%2fissues%2f87%23issuecomment%2d1031929445&umid=2228b5b7-eb8d-4e83-bdb9-cfa0adbdf288&auth=ba40f14edb9fac94ddb78b906f7486a30b35689c-14ef0b20740784542f4c9af6fca036d0db56bf8a>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fAJAG6WPKWHL37ZY6VBYULMDU2AYRVANCNFSM5NW2C2HA&umid=2228b5b7-eb8d-4e83-bdb9-cfa0adbdf288&auth=ba40f14edb9fac94ddb78b906f7486a30b35689c-d43e7c77d97e121b055f6ac8a2b42d6cb7a8de70>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by testcop** [comment]
fix pushed to JetBrains - give it a couple of days before it is available - issue was introduced as recompile with R# version
2021.3 1.10.15.7

thanks for using TestCop...
