### ISSUE TITLE
Needs a recompile for ReSharper 2022.1.1

### ISSUE THREAD

**Issue by astrohart** [testcop/Resharper.TestCop#89]
Hi,

I request you please recompile this for the latest version of ReSharper, which is 2022.1.1.

Thank you.

Regards,

Brian Hart

**Comment by testcop** [comment]
taking a look.
Pull Requests welcomed...

**Comment by SchreinerK** [comment]
> Pull Requests welcomed...

On first view, there are 80! referenced packages. too much to know which one needs to be updated w/o prior knowledge

**Comment by rayphi** [comment]
@SchreinerK as mentioned over here https://github.com/testcop/Resharper.TestCop/issues/68#issuecomment-846812554
You have to:
* Open up manage NuGet Packages for Solution
  * upgrade JetBrains.Resharper.SDK Nuget package
  * upgrade JetBrains.Resharper.SDK.Tests Nuget package
* Close project and reopen – _For me, it has worked without this step so far._
* Now, compile and fix breakages – hardest part  
* Run unit tests (they are slow but pass)
* Update ReleaseNotes and version information in Project\Src\InstallSupport\TestCop.nuspec and Project\Src\TestCop.Plugin\Properties\AssemblyInfo.cs
* Now you can set a source directory in the menu "Resharper > Options > Extension Manager" where the new Nuget package is located. Then you can open the Extension Manager and install your new version.

**Comment by testcop** [comment]
Pushed to Jetbrains. Many thanks @rayphi
